### ISSUE TITLE
Left/right-align install-table column to make scanning down it easier

### ISSUE THREAD

**Issue by Jonta** [polybar/polybar.github.io#27]
See e.g. 150 words of https://practicaltypography.com/centered-text.html

Referring to the column of operating system names. =)

E: "Left/right" in case of l10n for right-to-left languages

**Comment by TonCherAmi** [comment]
Right-aligning the names does seem to look nicer, feel free to send a patch if you'd like.

**Comment by Jonta** [comment]
> Right-aligning the names does seem to look nicer, feel free to send a patch if you'd like.

@TonCherAmi I would if I could. I looked for a few minutes to find the relevant piece of code a few days ago, and now for at least 10 minutes, installing Ruby and getting the site to run on localhost

**Comment by Jonta** [comment]
@patrick96 Why right-align for English instead of left-align? =)

**Comment by patrick96** [comment]
Because it looks nicer. I would have actually preferred center align to left align
