### ISSUE TITLE
CSS: "!important" in a bunch of places

### ISSUE THREAD

**Issue by Jonta** [polybar/polybar.github.io#28]
```
git grep important | wc -l
29
```

Perhaps those are all there for good reasons

[I'm not experienced with Jekyll or Ruby](https://github.com/polybar/polybar.github.io/issues/27), but I'm leaving this issue here in case

I'd also be interested in working on it myself to learn more. =)

**Comment by TonCherAmi** [comment]
We use Bootstrap and styling it often requires using `!important`. Don't really think this needs fixing.

**Comment by Jonta** [comment]
The accepted answer here has 6 points: https://stackoverflow.com/questions/35709447/why-does-bootstrap-use-important-for-responsive-classes

Utility classes seem like a good use case: https://css-tricks.com/when-using-important-is-the-right-choice/

**Comment by patrick96** [comment]
Feel free to work on this. But this really isn't high, priority. Once could say it's not that *important* :sunglasses:

**Comment by Jonta** [comment]
I'm going to prioritise other things for now. Closing. =)
